In [1]:
print("hi")

hi


In [3]:
#importing
import numpy as np

In [4]:
#creating an array
a=np.array([1,2])

In [5]:
print(a)

[1 2]


In [6]:
#multidim array
b=np.array([[1,2],[4,5]])
print(b)

[[1 2]
 [4 5]]


In [7]:
#mentioning data type 
c=np.array([[1,2],[3,4]],dtype='int16')
print(c)

[[1 2]
 [3 4]]


In [8]:
#number of elements of array(rows)
print(a.ndim,b.ndim,c.ndim)

1 2 2


In [9]:
#dimensions of array(row,col)
#for one dimensional arrays no.of columns is only displayed 
print(a.shape,b.shape,c.shape)

(2,) (2, 2) (2, 2)


In [10]:

#number of bytes(=8 bits) taken by an element of array
print(a.itemsize,b.itemsize,c.itemsize)

4 4 2


In [11]:
#total number of elements (n1*n2*n2*n4.... where n1,n2,n3,n4...are dimensions on an array)
print(a.nbytes,b.nbytes,c.nbytes)

8 16 8


In [12]:
#accessing elements of an array [row,column]
print(a[0])

1


In [13]:
print(b[0])

[1 2]


In [14]:
print(b[:,0])

[1 4]


In [15]:
print(b[0,:])

[1 2]


In [26]:
print(b[0,:1])

[1]


In [27]:
#replacing elements
b[1,1]=7
print(b)

[[1 2]
 [4 7]]


In [28]:
b[0,:]=7
print(b)

[[7 7]
 [4 7]]


In [35]:
#weird ways of creating arrays
#all zeroes
d=np.zeros(9,dtype='int16')
print(d)

[0 0 0 0 0 0 0 0 0]


In [36]:
print(d)

[0 0 0 0 0 0 0 0 0]


In [37]:
e=np.full([3,4],0)
print(e)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [38]:
#having same dimensions as another array
f=np.full_like(b,4)
print(f)

[[4 4]
 [4 4]]


In [39]:
#having randomly generated elements
g=np.random_rand(2,3)

AttributeError: module 'numpy' has no attribute 'random_rand'

In [40]:
g=np.random.rand(2,3)
print(g)



[[0.06319492 0.313286   0.64481739]
 [0.28189733 0.01076037 0.92013147]]


In [41]:
h=np.random.random_sample(a)
print(h)

[[0.19823169 0.62724744]]


In [45]:
#random but having dim of a given
h=np.random.random_sample(b.shape)
print(h)

[[0.91225753 0.76872928]
 [0.74578365 0.32985132]]


In [49]:
#using randint
i=np.random.randint(5,size=(2,2))
print(i)

[[1 4]
 [0 3]]


In [50]:
i=np.random.randint(5,22,size=(2,2))
print(i)

[[ 5  7]
 [11  5]]


In [52]:
#IDENITY MATRIX
j=np.identity(7)
print(j)

[[1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1.]]


In [59]:
#repeating a matrix
a=np.array([[1,2],[3,4]])
k=np.repeat(a,4,axis=0)
print(a,k,sep="\n")
print(k.shape,a.shape)

[[1 2]
 [3 4]]
[[1 2]
 [1 2]
 [1 2]
 [1 2]
 [3 4]
 [3 4]
 [3 4]
 [3 4]]
(8, 2) (2, 2)


In [60]:
k=np.repeat(a,4,axis=1)
print(k)

[[1 1 1 1 2 2 2 2]
 [3 3 3 3 4 4 4 4]]


In [68]:
#some cool stuff
l=np.ones((7,7))
print(l)
m=np.identity(5)
print(m)
m[2,2]=6
l[1:6,1:6]=m
print(l)
print(m)


[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 0. 0. 0. 0. 1.]
 [1. 0. 1. 0. 0. 0. 1.]
 [1. 0. 0. 6. 0. 0. 1.]
 [1. 0. 0. 0. 1. 0. 1.]
 [1. 0. 0. 0. 0. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 6. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [70]:
#careful of copies
a=np.array([1,2])
b=a
b[0]=100
print(a,b)

[100   2] [100   2]


In [74]:
#some matrix stuff
print(a+2,a/2,a**2)
a1=np.array([[1,2],[2,3]])
a2=np.array([[2,3,4],[3,4,5]])
#matrix mult
a3=np.matmul(a1,a2)
print(a3)

[102   4] [50.  1.] [10000     4]
[[ 8 11 14]
 [13 18 23]]


In [76]:
#reshaping an array
#a3.shape=(3,2) or
a3.reshape(3,2)
print(a3)

[[ 8 11 14]
 [13 18 23]]


In [1]:
#range option
print(list(range(4)))

[0, 1, 2, 3]


In [16]:
#using fromiter (iterobj,dtyep,count)
x=list(range(4))
r=np.fromiter(x,dtype='int16')
print(r)

[0 1 2 3]


In [17]:
#using arange option(start,stop(exc),step,dtype)
print(np.arange(1,7,dtype="int16"))

[1 2 3 4 5 6]


In [18]:
print(np.arange(1,7,2,dtype="float"))

[1. 3. 5.]


In [19]:
#using linspace DOUBT

In [22]:
#central tendencies
a=np.random.randint(0,100,size=(5,))
print(a)
x=np.mean(a)
print(x)

[69 72 81 86 46]
70.8


In [23]:
x=np.median(a)
print(x)

72.0


In [27]:
#FOR MODE IMPORT STATS FROM SCIPY
from scipy import stats
a=[1,1,1,2,3,3]
x=stats.mode(a)

print(x)

ModeResult(mode=array([1]), count=array([3]))


In [28]:
#spread of data abt central tend
#for more info visit link https://numpy.org/doc/stable/reference/generated/numpy.var.html
print(np.std(a))
print(np.var(a))

0.8975274678557508
0.8055555555555557


In [30]:
#UNIFORM DIST. FUNC 
from numpy import random

x = random.uniform(2,3,size=(2, 3))

print(x)

[[2.43708507 2.27182119 2.87702368]
 [2.42010544 2.44773888 2.8402335 ]]
